"""init2

Revision ID: 4317acf93df3
Revises: 4a04b9c2e2c9
Create Date: 2022-09-29 23:51:31.103315

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4317acf93df3'
down_revision = '4a04b9c2e2c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
