"""init2

Revision ID: 4a04b9c2e2c9
Revises: 5db2ff117c66
Create Date: 2022-09-29 23:49:45.832551

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4a04b9c2e2c9'
down_revision = '5db2ff117c66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
