"""post indexes

Revision ID: 4d3f92b418fc
Revises: d86c75053019
Create Date: 2022-10-21 21:27:06.595325

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4d3f92b418fc'
down_revision = 'd86c75053019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_owner_id'), 'posts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_posts_parent_id'), 'posts', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_parent_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_owner_id'), table_name='posts')
    # ### end Alembic commands ###
