"""remove post_id

Revision ID: 522b4a596df8
Revises: 3c72cfb6a800
Create Date: 2022-10-04 17:46:38.328975

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '522b4a596df8'
down_revision = '3c72cfb6a800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_post_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_post_id_fkey', 'posts', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
