"""init2

Revision ID: 5db2ff117c66
Revises: 293488c49995
Create Date: 2022-09-29 14:44:06.096979

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5db2ff117c66'
down_revision = '293488c49995'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
