"""init2

Revision ID: 6f0d30448cca
Revises: 4317acf93df3
Create Date: 2022-09-29 23:56:43.790451

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6f0d30448cca'
down_revision = '4317acf93df3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
