name: Test action
on: [ push ]

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.0-alpine
        env:
          POSTGRES_PASSWORD: a73147b7f8a246965a699b4df153
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Start Test DB
        run: docker-compose up -d db_test
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install poetry==1.1.13
          poetry install
      - name: Run tests
        env:
          DATABASE_URL: 'postgresql+asyncpg://postgres:postgres@127.0.0.1:15432/postgres'
          SECRET_KEY: 'you-will-never-guess'
        run: |
          poetry run sh -c "pytest . -v"
